const fs = require("fs")
const path = require("path")
const prompts = require('prompts');

const detectors = require("../../src/detectors")
const scanner = require("../../src/scanner")
const interactive = require("../../src/interactive")

const projectRoot = process.cwd();

const i18n = {
  en: {
    // Sections
    projectInfo: "Project Info",
    projectStructure: "Project Structure",
    techStack: "Tech Stack",
    gettingStarted: "Getting Started",
    environmentVariables: "Environment Variables",
    databaseSetup: "Database Setup",
    server: "Server",

    // Labels
    version: "Version",
    packageManager: "Package Manager",
    type: "Type",
    generatedBy: "Generated by",

    // Text blocks
    notSpecified: "Not specified",
    createEnvFile: "Create a `.env` file in the project root with the following variables:",
    runMigrations: "Run Prisma migrations:",
    serverRunning: "After starting, the server will run at:",

    // Project types
    nodeProject: "Node.js Project",
    frontendReact: "React Frontend",
    nextApp: "Next.js Application",
    expressApi: "REST API (Express)",
    typescriptProject: "TypeScript Project"
  },

  pt: {
    projectInfo: "Informações do Projeto",
    projectStructure: "Estrutura do Projeto",
    techStack: "Tecnologias",
    gettingStarted: "Primeiros Passos",
    environmentVariables: "Variáveis de Ambiente",
    databaseSetup: "Configuração do Banco de Dados",
    server: "Servidor",

    version: "Versão",
    packageManager: "Gerenciador de Pacotes",
    type: "Tipo",
    generatedBy: "Gerado por",

    notSpecified: "Não especificado",
    createEnvFile: "Crie um arquivo `.env` na raiz do projeto com as seguintes variáveis:",
    runMigrations: "Execute as migrations do Prisma:",
    serverRunning: "Após iniciar, o servidor estará disponível em:",

    nodeProject: "Projeto Node.js",
    frontendReact: "Frontend React",
    nextApp: "Aplicação Next.js",
    expressApi: "API REST (Express)",
    typescriptProject: "Projeto TypeScript"
  },

  es: {
    projectInfo: "Información del Proyecto",
    projectStructure: "Estructura del Proyecto",
    techStack: "Stack Tecnológico",
    gettingStarted: "Primeros Pasos",
    environmentVariables: "Variables de Entorno",
    databaseSetup: "Configuración de Base de Datos",
    server: "Servidor",

    version: "Versión",
    packageManager: "Administrador de Paquetes",
    type: "Tipo",
    generatedBy: "Generado por",

    notSpecified: "No especificado",
    createEnvFile: "Crea un archivo `.env` en la raíz del proyecto con las siguientes variables:",
    runMigrations: "Ejecuta las migraciones de Prisma:",
    serverRunning: "Después de iniciar, el servidor estará disponible en:",

    nodeProject: "Proyecto Node.js",
    frontendReact: "Frontend React",
    nextApp: "Aplicación Next.js",
    expressApi: "API REST (Express)",
    typescriptProject: "Proyecto TypeScript"
  }
}


async function generateReadme(packageJson, tree, config){

  const deps = {
    ...packageJson.dependencies,
    ...packageJson.devDependencies
  }

  const techStack = detectors.detectarTechStack(deps)
  const techSection = gerarTechStackSection(techStack)




  const envVars = detectors.detectarEnvVars(projectRoot)
  const envSection = gerarEnvSection(envVars)

  const nomeProjeto = await interactive.buscarNome(packageJson.name);
  const descricaoProjeto = await interactive.buscarDescricao(packageJson.description);
  const idioma = await interactive.escolherLingua()
  const t = i18n[idioma] || i18n.en

  const packageManager = detectors.detectarPackageManager(projectRoot)

  const scanData = scanner.scanProjectFiles(projectRoot)
  let port = detectors.detectarPorta(scanData)

  if (!port) {
    port = await interactive.perguntarPortaManual()
  }

  const hasPrisma = detectors.detectarPrisma(projectRoot, packageJson)
  const dbSection = hasPrisma ? gerarDatabaseSection(packageManager) : ""

  const gettingStartedCommands = gerarGettingStarted(
    packageManager,
    packageJson.scripts,
    hasPrisma
  )



const content = `
# ${nomeProjeto}

${descricaoProjeto}

## ${config.emojis ? "🔖" : ""} ${t.projectInfo}
- **${t.version}:** ${packageJson.version || t.notSpecified}
- **${t.packageManager}:** ${packageManager}
- **${t.type}:** ${detectarTipoProjeto(packageJson)}

## 🛠 ${t.techStack}
${techSection}

## ${config.emojis ? "📁" : ""} ${t.projectStructure}
\`\`\`
${tree}
\`\`\`

## 🚀 ${t.gettingStarted}
${gettingStartedCommands}

## 🔑 ${t.environmentVariables}
${t.createEnvFile}
${envSection}

## 🗄 ${t.databaseSetup}
${t.runMigrations}
${dbSection}

${port ? `
## 🌐 ${t.server}

${t.serverRunning}

http://localhost:${port}

` : ""}


---

${t.generatedBy} **mdSmith**
`
    
    return content 

}

function getRunCommand(script, packageManager) {
  if (packageManager === "yarn") return `yarn ${script}`
  if (packageManager === "pnpm") return `pnpm ${script}`
  return `npm run ${script}`
}

function detectarTipoProjeto(packageJson) {
    const deps = {
        ...packageJson.dependencies,
        ...packageJson.devDependencies
    }

    if (deps.react) return "Frontend React"
    if (deps.next) return "Next.js Application"
    if (deps.express) return "API REST (Express)"
    if (deps.typescript) return "Projeto TypeScript"

    return "Node.js Project"
}


function gerarEnvSection(vars) {
  if (!vars.length) return ""

  let section = "\n\n"

  vars.forEach(v => {
    section += `- ${v}\n`
  })

  return section + "\n"
}

function gerarDatabaseSection(packageManager) {
  let section = "\n\n"
  section += "\n\n"
  section += "```bash\n"

  if (packageManager === "npm") {
    section += "npx prisma migrate dev\n"
    section += "npx prisma generate\n"
  } else {
    section += "npx prisma migrate dev\n"
    section += "npx prisma generate\n"
  }

  section += "```\n\n"

  return section
}


function gerarGettingStarted(packageManager = "npm", scripts = {}, hasPrisma) {
  const lines = []

  lines.push(
    packageManager === "npm"
      ? "npm install"
      : `${packageManager} install`
  )

  if (hasPrisma) {
    lines.push("npx prisma migrate dev")
  }

  if (scripts.dev) {
    lines.push(getRunCommand("dev", packageManager))
  } else if (scripts.start) {
    lines.push(getRunCommand("start", packageManager))
  }

  return `

\`\`\`bash
${lines.join("\n")}
\`\`\`

`
}

function gerarTechStackSection(stack) {
  if (!stack.length) return ""

  let section = "\n\n"

  stack.forEach(tech => {
    section += `- ${tech}\n`
  })

  return section + "\n"
}




module.exports = {
generateReadme,
gerarEnvSection,
gerarDatabaseSection,
gerarGettingStarted,
gerarTechStackSection
}